-- AlterTable
ALTER TABLE "Campaign" ADD COLUMN     "noOfEmails" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "noOfSMS" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "noOfWhatsApp" INTEGER NOT NULL DEFAULT 0;
